### ISSUE TITLE
有16:9的版本吗？谢谢

### ISSUE THREAD

**Issue by zhanglinbo** [icgw/latex-templates#1]
有16:9的版本吗？谢谢

**Comment by icgw** [comment]
第 1 行，更改如下：
```tex
\documentclass[10pt,utf8,aspectratio=169]{beamer}
```
+ 增加 `aspectraio=169` 选项设置，表示页面大小为：宽 160mm，高 90mm
> 更多内容参见 The Beamer Class User Guide 第77页
